# Generated by Django 6.0.1 on 2026-02-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0002_pickuprequest_assigned_collector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='segregation_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='suggested_waste_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
